export const HANDLE_INGREDIENT = 'HANDLE_INGREDIENT';
export const CLEAR_ODER = 'CLEAR_ODER';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';